"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import protos.event.entity_pb2
import protos.event.monitor_pb2
import protos.event.trigger_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AlertSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TRIGGER_FIELD_NUMBER: builtins.int
    ENTITY_TRIGGER_FIELD_NUMBER: builtins.int
    TRIGGERED_AT_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def trigger(self) -> protos.event.trigger_pb2.TriggerSummary: ...
    @property
    def entity_trigger(self) -> protos.event.entity_pb2.EntityTrigger: ...
    triggered_at: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        trigger: protos.event.trigger_pb2.TriggerSummary | None = ...,
        entity_trigger: protos.event.entity_pb2.EntityTrigger | None = ...,
        triggered_at: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity_trigger", b"entity_trigger", "trigger", b"trigger"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity_trigger", b"entity_trigger", "id", b"id", "trigger", b"trigger", "triggered_at", b"triggered_at"]) -> None: ...

global___AlertSummary = AlertSummary

@typing_extensions.final
class AlertStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_TRANSACTION_COUNT_FIELD_NUMBER: builtins.int
    MISSED_TRANSACTION_COUNT_FIELD_NUMBER: builtins.int
    DELAYED_TRANSACTION_COUNT_FIELD_NUMBER: builtins.int
    MEDIAN_DELAY_FIELD_NUMBER: builtins.int
    EVENT_NAME_FIELD_NUMBER: builtins.int
    EVENT_KEY_NAME_FIELD_NUMBER: builtins.int
    EVENT_TIMESTAMP_FIELD_NUMBER: builtins.int
    ENTITY_INSTANCE_VALUE_FIELD_NUMBER: builtins.int
    @property
    def total_transaction_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def missed_transaction_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def delayed_transaction_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def median_delay(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def event_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def event_key_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def event_timestamp(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def entity_instance_value(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        total_transaction_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        missed_transaction_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        delayed_transaction_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        median_delay: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        event_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        event_key_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        event_timestamp: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        entity_instance_value: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delayed_transaction_count", b"delayed_transaction_count", "entity_instance_value", b"entity_instance_value", "event_key_name", b"event_key_name", "event_name", b"event_name", "event_timestamp", b"event_timestamp", "median_delay", b"median_delay", "missed_transaction_count", b"missed_transaction_count", "total_transaction_count", b"total_transaction_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["delayed_transaction_count", b"delayed_transaction_count", "entity_instance_value", b"entity_instance_value", "event_key_name", b"event_key_name", "event_name", b"event_name", "event_timestamp", b"event_timestamp", "median_delay", b"median_delay", "missed_transaction_count", b"missed_transaction_count", "total_transaction_count", b"total_transaction_count"]) -> None: ...

global___AlertStats = AlertStats

@typing_extensions.final
class AlertDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TRIGGER_FIELD_NUMBER: builtins.int
    ENTITY_TRIGGER_FIELD_NUMBER: builtins.int
    TRIGGERED_AT_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    id: builtins.int
    @property
    def trigger(self) -> protos.event.trigger_pb2.Trigger: ...
    @property
    def entity_trigger(self) -> protos.event.entity_pb2.EntityTrigger: ...
    @property
    def triggered_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def stats(self) -> global___AlertStats: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        trigger: protos.event.trigger_pb2.Trigger | None = ...,
        entity_trigger: protos.event.entity_pb2.EntityTrigger | None = ...,
        triggered_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stats: global___AlertStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity_trigger", b"entity_trigger", "stats", b"stats", "trigger", b"trigger", "triggered_at", b"triggered_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity_trigger", b"entity_trigger", "id", b"id", "stats", b"stats", "trigger", b"trigger", "triggered_at", b"triggered_at"]) -> None: ...

global___AlertDetail = AlertDetail

@typing_extensions.final
class DelayedMonitorTransactionStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELAY_DURATION_FIELD_NUMBER: builtins.int
    @property
    def delay_duration(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    def __init__(
        self,
        *,
        delay_duration: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delay_duration", b"delay_duration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["delay_duration", b"delay_duration"]) -> None: ...

global___DelayedMonitorTransactionStats = DelayedMonitorTransactionStats

@typing_extensions.final
class AlertMonitorTransaction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AlertMonitorTransaction._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: AlertMonitorTransaction._Type.ValueType  # 0
        MISSED_TRANSACTION: AlertMonitorTransaction._Type.ValueType  # 1
        DELAYED_TRANSACTION: AlertMonitorTransaction._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: AlertMonitorTransaction.Type.ValueType  # 0
    MISSED_TRANSACTION: AlertMonitorTransaction.Type.ValueType  # 1
    DELAYED_TRANSACTION: AlertMonitorTransaction.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    MONITOR_TRANSACTION_FIELD_NUMBER: builtins.int
    ALERT_ID_FIELD_NUMBER: builtins.int
    DELAYED_MONITOR_TRANSACTION_STATS_FIELD_NUMBER: builtins.int
    TRIGGER_NAME_FIELD_NUMBER: builtins.int
    type: global___AlertMonitorTransaction.Type.ValueType
    @property
    def monitor_transaction(self) -> protos.event.monitor_pb2.MonitorTransaction: ...
    alert_id: builtins.int
    @property
    def delayed_monitor_transaction_stats(self) -> global___DelayedMonitorTransactionStats: ...
    trigger_name: builtins.str
    def __init__(
        self,
        *,
        type: global___AlertMonitorTransaction.Type.ValueType = ...,
        monitor_transaction: protos.event.monitor_pb2.MonitorTransaction | None = ...,
        alert_id: builtins.int = ...,
        delayed_monitor_transaction_stats: global___DelayedMonitorTransactionStats | None = ...,
        trigger_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delayed_monitor_transaction_stats", b"delayed_monitor_transaction_stats", "monitor_transaction", b"monitor_transaction", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id", "delayed_monitor_transaction_stats", b"delayed_monitor_transaction_stats", "monitor_transaction", b"monitor_transaction", "stats", b"stats", "trigger_name", b"trigger_name", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["stats", b"stats"]) -> typing_extensions.Literal["delayed_monitor_transaction_stats"] | None: ...

global___AlertMonitorTransaction = AlertMonitorTransaction

@typing_extensions.final
class AlertEntityInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AlertEntityInstance._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: AlertEntityInstance._Type.ValueType  # 0
        PER_EVENT: AlertEntityInstance._Type.ValueType  # 1
        AGGREGATED_EVENTS: AlertEntityInstance._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: AlertEntityInstance.Type.ValueType  # 0
    PER_EVENT: AlertEntityInstance.Type.ValueType  # 1
    AGGREGATED_EVENTS: AlertEntityInstance.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    ENTITY_INSTANCE_FIELD_NUMBER: builtins.int
    ALERT_ID_FIELD_NUMBER: builtins.int
    TRIGGER_NAME_FIELD_NUMBER: builtins.int
    type: global___AlertEntityInstance.Type.ValueType
    @property
    def entity_instance(self) -> protos.event.entity_pb2.EntityInstance: ...
    alert_id: builtins.int
    trigger_name: builtins.str
    def __init__(
        self,
        *,
        type: global___AlertEntityInstance.Type.ValueType = ...,
        entity_instance: protos.event.entity_pb2.EntityInstance | None = ...,
        alert_id: builtins.int = ...,
        trigger_name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity_instance", b"entity_instance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alert_id", b"alert_id", "entity_instance", b"entity_instance", "trigger_name", b"trigger_name", "type", b"type"]) -> None: ...

global___AlertEntityInstance = AlertEntityInstance
