"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.event.base_pb2
import protos.event.notification_pb2
import protos.event.query_base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EntityEventKeyMapping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    EVENT_KEY_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def event_key(self) -> protos.event.base_pb2.EventKey: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        event_key: protos.event.base_pb2.EventKey | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_key", b"event_key", "id", b"id", "is_active", b"is_active"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_key", b"event_key", "id", b"id", "is_active", b"is_active"]) -> None: ...

global___EntityEventKeyMapping = EntityEventKeyMapping

@typing_extensions.final
class EntityTriggerDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TriggerType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TriggerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EntityTriggerDefinition._TriggerType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_TYPE: EntityTriggerDefinition._TriggerType.ValueType  # 0
        PER_EVENT: EntityTriggerDefinition._TriggerType.ValueType  # 1
        AGGREGATED_EVENTS: EntityTriggerDefinition._TriggerType.ValueType  # 2

    class TriggerType(_TriggerType, metaclass=_TriggerTypeEnumTypeWrapper): ...
    UNKNOWN_TYPE: EntityTriggerDefinition.TriggerType.ValueType  # 0
    PER_EVENT: EntityTriggerDefinition.TriggerType.ValueType  # 1
    AGGREGATED_EVENTS: EntityTriggerDefinition.TriggerType.ValueType  # 2

    class _EntityTriggerRuleType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EntityTriggerRuleTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EntityTriggerDefinition._EntityTriggerRuleType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: EntityTriggerDefinition._EntityTriggerRuleType.ValueType  # 0
        LAST_EVENT: EntityTriggerDefinition._EntityTriggerRuleType.ValueType  # 1
        EVENT_COUNT: EntityTriggerDefinition._EntityTriggerRuleType.ValueType  # 2
        EVENT_OCCURS: EntityTriggerDefinition._EntityTriggerRuleType.ValueType  # 3

    class EntityTriggerRuleType(_EntityTriggerRuleType, metaclass=_EntityTriggerRuleTypeEnumTypeWrapper): ...
    UNKNOWN: EntityTriggerDefinition.EntityTriggerRuleType.ValueType  # 0
    LAST_EVENT: EntityTriggerDefinition.EntityTriggerRuleType.ValueType  # 1
    EVENT_COUNT: EntityTriggerDefinition.EntityTriggerRuleType.ValueType  # 2
    EVENT_OCCURS: EntityTriggerDefinition.EntityTriggerRuleType.ValueType  # 3

    @typing_extensions.final
    class TriggerRuleConfig(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        EVENT_ID_FIELD_NUMBER: builtins.int
        TIME_INTERVAL_FIELD_NUMBER: builtins.int
        THRESHOLD_COUNT_FIELD_NUMBER: builtins.int
        EVENT_NAME_FIELD_NUMBER: builtins.int
        event_id: builtins.int
        time_interval: builtins.int
        threshold_count: builtins.int
        event_name: builtins.str
        def __init__(
            self,
            *,
            event_id: builtins.int = ...,
            time_interval: builtins.int = ...,
            threshold_count: builtins.int = ...,
            event_name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["event_id", b"event_id", "event_name", b"event_name", "threshold_count", b"threshold_count", "time_interval", b"time_interval"]) -> None: ...

    RULE_TYPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TRIGGER_RULE_CONFIG_FIELD_NUMBER: builtins.int
    rule_type: global___EntityTriggerDefinition.EntityTriggerRuleType.ValueType
    type: global___EntityTriggerDefinition.TriggerType.ValueType
    @property
    def trigger_rule_config(self) -> global___EntityTriggerDefinition.TriggerRuleConfig: ...
    def __init__(
        self,
        *,
        rule_type: global___EntityTriggerDefinition.EntityTriggerRuleType.ValueType = ...,
        type: global___EntityTriggerDefinition.TriggerType.ValueType = ...,
        trigger_rule_config: global___EntityTriggerDefinition.TriggerRuleConfig | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["trigger_rule_config", b"trigger_rule_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["rule_type", b"rule_type", "trigger_rule_config", b"trigger_rule_config", "type", b"type"]) -> None: ...

global___EntityTriggerDefinition = EntityTriggerDefinition

@typing_extensions.final
class EntityTrigger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ENTITY_ID_FIELD_NUMBER: builtins.int
    ENTITY_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    id: builtins.int
    entity_id: builtins.int
    entity_name: builtins.str
    name: builtins.str
    @property
    def definition(self) -> global___EntityTriggerDefinition: ...
    @property
    def filter(self) -> protos.event.query_base_pb2.Filter: ...
    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.notification_pb2.NotificationConfig]: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        entity_id: builtins.int = ...,
        entity_name: builtins.str = ...,
        name: builtins.str = ...,
        definition: global___EntityTriggerDefinition | None = ...,
        filter: protos.event.query_base_pb2.Filter | None = ...,
        notifications: collections.abc.Iterable[protos.event.notification_pb2.NotificationConfig] | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["definition", b"definition", "filter", b"filter", "is_active", b"is_active"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["definition", b"definition", "entity_id", b"entity_id", "entity_name", b"entity_name", "filter", b"filter", "id", b"id", "is_active", b"is_active", "name", b"name", "notifications", b"notifications"]) -> None: ...

global___EntityTrigger = EntityTrigger

@typing_extensions.final
class Entity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Entity._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Entity._Type.ValueType  # 0
        DEFAULT: Entity._Type.ValueType  # 1
        FUNNEL: Entity._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: Entity.Type.ValueType  # 0
    DEFAULT: Entity.Type.ValueType  # 1
    FUNNEL: Entity.Type.ValueType  # 2

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    created_at: builtins.int
    updated_at: builtins.int
    type: global___Entity.Type.ValueType
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        created_at: builtins.int = ...,
        updated_at: builtins.int = ...,
        type: global___Entity.Type.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id", "is_active", b"is_active", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "id", b"id", "is_active", b"is_active", "name", b"name", "type", b"type", "updated_at", b"updated_at"]) -> None: ...

global___Entity = Entity

@typing_extensions.final
class EntityPartial(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name"]) -> None: ...

global___EntityPartial = EntityPartial

@typing_extensions.final
class EntityStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NEW_INSTANCE_COUNT_FIELD_NUMBER: builtins.int
    ACTIVE_INSTANCE_COUNT_FIELD_NUMBER: builtins.int
    EVENT_COUNT_FIELD_NUMBER: builtins.int
    TRANSACTION_COUNT_FIELD_NUMBER: builtins.int
    @property
    def new_instance_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def active_instance_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def transaction_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        new_instance_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        active_instance_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        transaction_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["active_instance_count", b"active_instance_count", "event_count", b"event_count", "new_instance_count", b"new_instance_count", "transaction_count", b"transaction_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_instance_count", b"active_instance_count", "event_count", b"event_count", "new_instance_count", b"new_instance_count", "transaction_count", b"transaction_count"]) -> None: ...

global___EntityStats = EntityStats

@typing_extensions.final
class EntitySummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> global___Entity: ...
    @property
    def stats(self) -> global___EntityStats: ...
    def __init__(
        self,
        *,
        entity: global___Entity | None = ...,
        stats: global___EntityStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity", b"entity", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity", b"entity", "stats", b"stats"]) -> None: ...

global___EntitySummary = EntitySummary

@typing_extensions.final
class EntityDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    ENTITY_EVENT_KEY_MAPPINGS_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> global___Entity: ...
    @property
    def entity_event_key_mappings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityEventKeyMapping]: ...
    @property
    def stats(self) -> global___EntityStats: ...
    def __init__(
        self,
        *,
        entity: global___Entity | None = ...,
        entity_event_key_mappings: collections.abc.Iterable[global___EntityEventKeyMapping] | None = ...,
        stats: global___EntityStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity", b"entity", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity", b"entity", "entity_event_key_mappings", b"entity_event_key_mappings", "stats", b"stats"]) -> None: ...

global___EntityDetail = EntityDetail

@typing_extensions.final
class EntityInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    ENTITY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def instance(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def entity(self) -> global___EntityPartial: ...
    created_at: builtins.int
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        instance: google.protobuf.wrappers_pb2.StringValue | None = ...,
        entity: global___EntityPartial | None = ...,
        created_at: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity", b"entity", "id", b"id", "instance", b"instance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "entity", b"entity", "id", b"id", "instance", b"instance"]) -> None: ...

global___EntityInstance = EntityInstance

@typing_extensions.final
class EntityInstancePartial(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def instance(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        instance: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id", "instance", b"instance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "instance", b"instance"]) -> None: ...

global___EntityInstancePartial = EntityInstancePartial

@typing_extensions.final
class EntityInstanceStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_COUNT_FIELD_NUMBER: builtins.int
    TRANSACTION_COUNT_FIELD_NUMBER: builtins.int
    HAS_ALERTS_FIELD_NUMBER: builtins.int
    @property
    def event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def transaction_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def has_alerts(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        transaction_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        has_alerts: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event_count", b"event_count", "has_alerts", b"has_alerts", "transaction_count", b"transaction_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_count", b"event_count", "has_alerts", b"has_alerts", "transaction_count", b"transaction_count"]) -> None: ...

global___EntityInstanceStats = EntityInstanceStats

@typing_extensions.final
class EntityInstanceSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_INSTANCE_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    @property
    def entity_instance(self) -> global___EntityInstancePartial: ...
    @property
    def stats(self) -> global___EntityInstanceStats: ...
    def __init__(
        self,
        *,
        entity_instance: global___EntityInstancePartial | None = ...,
        stats: global___EntityInstanceStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity_instance", b"entity_instance", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity_instance", b"entity_instance", "stats", b"stats"]) -> None: ...

global___EntityInstanceSummary = EntityInstanceSummary

@typing_extensions.final
class EntityInstanceDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_INSTANCE_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    @property
    def entity_instance(self) -> global___EntityInstance: ...
    @property
    def stats(self) -> global___EntityInstanceStats: ...
    def __init__(
        self,
        *,
        entity_instance: global___EntityInstance | None = ...,
        stats: global___EntityInstanceStats | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entity_instance", b"entity_instance", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entity_instance", b"entity_instance", "stats", b"stats"]) -> None: ...

global___EntityInstanceDetail = EntityInstanceDetail

@typing_extensions.final
class EntityInstanceGetParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANCES_FIELD_NUMBER: builtins.int
    @property
    def instances(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        instances: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["instances", b"instances"]) -> None: ...

global___EntityInstanceGetParams = EntityInstanceGetParams

@typing_extensions.final
class UpdateEntityOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateEntityOp._Op.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateEntityOp._Op.ValueType  # 0
        UPDATE_ENTITY_NAME: UpdateEntityOp._Op.ValueType  # 1
        UPDATE_ENTITY_STATUS: UpdateEntityOp._Op.ValueType  # 2
        UPDATE_ENTITY_EVENT_KEY_MAPPING_STATUS: UpdateEntityOp._Op.ValueType  # 3
        ADD_ENTITY_EVENT_KEY_MAPPINGS: UpdateEntityOp._Op.ValueType  # 4
        REMOVE_ENTITY_EVENT_KEY_MAPPINGS: UpdateEntityOp._Op.ValueType  # 5

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateEntityOp.Op.ValueType  # 0
    UPDATE_ENTITY_NAME: UpdateEntityOp.Op.ValueType  # 1
    UPDATE_ENTITY_STATUS: UpdateEntityOp.Op.ValueType  # 2
    UPDATE_ENTITY_EVENT_KEY_MAPPING_STATUS: UpdateEntityOp.Op.ValueType  # 3
    ADD_ENTITY_EVENT_KEY_MAPPINGS: UpdateEntityOp.Op.ValueType  # 4
    REMOVE_ENTITY_EVENT_KEY_MAPPINGS: UpdateEntityOp.Op.ValueType  # 5

    @typing_extensions.final
    class UpdateEntityName(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

    @typing_extensions.final
    class UpdateEntityStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> None: ...

    @typing_extensions.final
    class UpdateEntityEventKeyMappingStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENTITY_EVENT_KEY_MAPPING_ID_FIELD_NUMBER: builtins.int
        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def entity_event_key_mapping_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            entity_event_key_mapping_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["entity_event_key_mapping_id", b"entity_event_key_mapping_id", "is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["entity_event_key_mapping_id", b"entity_event_key_mapping_id", "is_active", b"is_active"]) -> None: ...

    @typing_extensions.final
    class AddEntityEventKeyMappings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        EVENT_KEY_IDS_FIELD_NUMBER: builtins.int
        @property
        def event_key_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            event_key_ids: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["event_key_ids", b"event_key_ids"]) -> None: ...

    @typing_extensions.final
    class RemoveEntityEventKeyMappings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENTITY_EVENT_KEY_MAPPING_IDS_FIELD_NUMBER: builtins.int
        @property
        def entity_event_key_mapping_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        def __init__(
            self,
            *,
            entity_event_key_mapping_ids: collections.abc.Iterable[builtins.int] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["entity_event_key_mapping_ids", b"entity_event_key_mapping_ids"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_ENTITY_NAME_FIELD_NUMBER: builtins.int
    UPDATE_ENTITY_STATUS_FIELD_NUMBER: builtins.int
    UPDATE_ENTITY_EVENT_KEY_MAPPING_STATUS_FIELD_NUMBER: builtins.int
    ADD_ENTITY_EVENT_KEY_MAPPINGS_FIELD_NUMBER: builtins.int
    REMOVE_ENTITY_EVENT_KEY_MAPPINGS_FIELD_NUMBER: builtins.int
    op: global___UpdateEntityOp.Op.ValueType
    @property
    def update_entity_name(self) -> global___UpdateEntityOp.UpdateEntityName: ...
    @property
    def update_entity_status(self) -> global___UpdateEntityOp.UpdateEntityStatus: ...
    @property
    def update_entity_event_key_mapping_status(self) -> global___UpdateEntityOp.UpdateEntityEventKeyMappingStatus: ...
    @property
    def add_entity_event_key_mappings(self) -> global___UpdateEntityOp.AddEntityEventKeyMappings: ...
    @property
    def remove_entity_event_key_mappings(self) -> global___UpdateEntityOp.RemoveEntityEventKeyMappings: ...
    def __init__(
        self,
        *,
        op: global___UpdateEntityOp.Op.ValueType = ...,
        update_entity_name: global___UpdateEntityOp.UpdateEntityName | None = ...,
        update_entity_status: global___UpdateEntityOp.UpdateEntityStatus | None = ...,
        update_entity_event_key_mapping_status: global___UpdateEntityOp.UpdateEntityEventKeyMappingStatus | None = ...,
        add_entity_event_key_mappings: global___UpdateEntityOp.AddEntityEventKeyMappings | None = ...,
        remove_entity_event_key_mappings: global___UpdateEntityOp.RemoveEntityEventKeyMappings | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["add_entity_event_key_mappings", b"add_entity_event_key_mappings", "remove_entity_event_key_mappings", b"remove_entity_event_key_mappings", "update", b"update", "update_entity_event_key_mapping_status", b"update_entity_event_key_mapping_status", "update_entity_name", b"update_entity_name", "update_entity_status", b"update_entity_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["add_entity_event_key_mappings", b"add_entity_event_key_mappings", "op", b"op", "remove_entity_event_key_mappings", b"remove_entity_event_key_mappings", "update", b"update", "update_entity_event_key_mapping_status", b"update_entity_event_key_mapping_status", "update_entity_name", b"update_entity_name", "update_entity_status", b"update_entity_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["update", b"update"]) -> typing_extensions.Literal["update_entity_name", "update_entity_status", "update_entity_event_key_mapping_status", "add_entity_event_key_mappings", "remove_entity_event_key_mappings"] | None: ...

global___UpdateEntityOp = UpdateEntityOp

@typing_extensions.final
class WorkflowView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _MetricStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _MetricStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WorkflowView._MetricStatus.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_METRIC_STATUS: WorkflowView._MetricStatus.ValueType  # 0
        GREEN: WorkflowView._MetricStatus.ValueType  # 1
        RED: WorkflowView._MetricStatus.ValueType  # 2

    class MetricStatus(_MetricStatus, metaclass=_MetricStatusEnumTypeWrapper): ...
    UNKNOWN_METRIC_STATUS: WorkflowView.MetricStatus.ValueType  # 0
    GREEN: WorkflowView.MetricStatus.ValueType  # 1
    RED: WorkflowView.MetricStatus.ValueType  # 2

    class _NodeStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _NodeStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WorkflowView._NodeStatus.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_NODE_STATUS: WorkflowView._NodeStatus.ValueType  # 0
        GOOD: WorkflowView._NodeStatus.ValueType  # 1
        BAD: WorkflowView._NodeStatus.ValueType  # 2

    class NodeStatus(_NodeStatus, metaclass=_NodeStatusEnumTypeWrapper): ...
    UNKNOWN_NODE_STATUS: WorkflowView.NodeStatus.ValueType  # 0
    GOOD: WorkflowView.NodeStatus.ValueType  # 1
    BAD: WorkflowView.NodeStatus.ValueType  # 2

    class _NodeConnectionType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _NodeConnectionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WorkflowView._NodeConnectionType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_CONNECTION_TYPE: WorkflowView._NodeConnectionType.ValueType  # 0
        IN: WorkflowView._NodeConnectionType.ValueType  # 1
        OUT: WorkflowView._NodeConnectionType.ValueType  # 2

    class NodeConnectionType(_NodeConnectionType, metaclass=_NodeConnectionTypeEnumTypeWrapper): ...
    UNKNOWN_CONNECTION_TYPE: WorkflowView.NodeConnectionType.ValueType  # 0
    IN: WorkflowView.NodeConnectionType.ValueType  # 1
    OUT: WorkflowView.NodeConnectionType.ValueType  # 2

    class _DeltaType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DeltaTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WorkflowView._DeltaType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN_DELTA_TYPE: WorkflowView._DeltaType.ValueType  # 0
        UP: WorkflowView._DeltaType.ValueType  # 1
        DOWN: WorkflowView._DeltaType.ValueType  # 2

    class DeltaType(_DeltaType, metaclass=_DeltaTypeEnumTypeWrapper): ...
    UNKNOWN_DELTA_TYPE: WorkflowView.DeltaType.ValueType  # 0
    UP: WorkflowView.DeltaType.ValueType  # 1
    DOWN: WorkflowView.DeltaType.ValueType  # 2

    @typing_extensions.final
    class Node(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class NodeMetric(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            NAME_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            METRIC_STATUS_FIELD_NUMBER: builtins.int
            METRIC_LINK_FIELD_NUMBER: builtins.int
            DELTA_FIELD_NUMBER: builtins.int
            DELTA_TYPE_FIELD_NUMBER: builtins.int
            @property
            def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            @property
            def value(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            metric_status: global___WorkflowView.MetricStatus.ValueType
            @property
            def metric_link(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            @property
            def delta(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
            delta_type: global___WorkflowView.DeltaType.ValueType
            def __init__(
                self,
                *,
                name: google.protobuf.wrappers_pb2.StringValue | None = ...,
                value: google.protobuf.wrappers_pb2.StringValue | None = ...,
                metric_status: global___WorkflowView.MetricStatus.ValueType = ...,
                metric_link: google.protobuf.wrappers_pb2.StringValue | None = ...,
                delta: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
                delta_type: global___WorkflowView.DeltaType.ValueType = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["delta", b"delta", "metric_link", b"metric_link", "name", b"name", "value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["delta", b"delta", "delta_type", b"delta_type", "metric_link", b"metric_link", "metric_status", b"metric_status", "name", b"name", "value", b"value"]) -> None: ...

        NODE_ID_FIELD_NUMBER: builtins.int
        LABEL_FIELD_NUMBER: builtins.int
        STATUS_FIELD_NUMBER: builtins.int
        CONNECTION_TYPES_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        WORKFLOW_NODE_CONFIG_FIELD_NUMBER: builtins.int
        @property
        def node_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def label(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        status: global___WorkflowView.NodeStatus.ValueType
        @property
        def connection_types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___WorkflowView.NodeConnectionType.ValueType]: ...
        @property
        def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WorkflowView.Node.NodeMetric]: ...
        @property
        def workflow_node_config(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            node_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            label: google.protobuf.wrappers_pb2.StringValue | None = ...,
            status: global___WorkflowView.NodeStatus.ValueType = ...,
            connection_types: collections.abc.Iterable[global___WorkflowView.NodeConnectionType.ValueType] | None = ...,
            metrics: collections.abc.Iterable[global___WorkflowView.Node.NodeMetric] | None = ...,
            workflow_node_config: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["label", b"label", "node_id", b"node_id", "workflow_node_config", b"workflow_node_config"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["connection_types", b"connection_types", "label", b"label", "metrics", b"metrics", "node_id", b"node_id", "status", b"status", "workflow_node_config", b"workflow_node_config"]) -> None: ...

    @typing_extensions.final
    class Edge(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing_extensions.final
        class EdgeMetric(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            NAME_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            METRIC_STATUS_FIELD_NUMBER: builtins.int
            @property
            def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            @property
            def value(self) -> google.protobuf.wrappers_pb2.StringValue: ...
            metric_status: global___WorkflowView.MetricStatus.ValueType
            def __init__(
                self,
                *,
                name: google.protobuf.wrappers_pb2.StringValue | None = ...,
                value: google.protobuf.wrappers_pb2.StringValue | None = ...,
                metric_status: global___WorkflowView.MetricStatus.ValueType = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["name", b"name", "value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["metric_status", b"metric_status", "name", b"name", "value", b"value"]) -> None: ...

        START_NODE_ID_FIELD_NUMBER: builtins.int
        END_NODE_ID_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        @property
        def start_node_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def end_node_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WorkflowView.Edge.EdgeMetric]: ...
        def __init__(
            self,
            *,
            start_node_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            end_node_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            metrics: collections.abc.Iterable[global___WorkflowView.Edge.EdgeMetric] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["end_node_id", b"end_node_id", "start_node_id", b"start_node_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["end_node_id", b"end_node_id", "metrics", b"metrics", "start_node_id", b"start_node_id"]) -> None: ...

    NODES_FIELD_NUMBER: builtins.int
    EDGES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WorkflowView.Node]: ...
    @property
    def edges(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WorkflowView.Edge]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[global___WorkflowView.Node] | None = ...,
        edges: collections.abc.Iterable[global___WorkflowView.Edge] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edges", b"edges", "nodes", b"nodes"]) -> None: ...

global___WorkflowView = WorkflowView

@typing_extensions.final
class FunnelView(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Node(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def value(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
            value: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class Edge(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SOURCE_FIELD_NUMBER: builtins.int
        TARGET_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        @property
        def source(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def target(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def value(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            source: google.protobuf.wrappers_pb2.StringValue | None = ...,
            target: google.protobuf.wrappers_pb2.StringValue | None = ...,
            value: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["source", b"source", "target", b"target", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["source", b"source", "target", b"target", "value", b"value"]) -> None: ...

    DATA_FIELD_NUMBER: builtins.int
    LINKS_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FunnelView.Node]: ...
    @property
    def links(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FunnelView.Edge]: ...
    def __init__(
        self,
        *,
        data: collections.abc.Iterable[global___FunnelView.Node] | None = ...,
        links: collections.abc.Iterable[global___FunnelView.Edge] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "links", b"links"]) -> None: ...

global___FunnelView = FunnelView
