# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/event/notification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/event/notification.proto\x12\x0cprotos.event\")\n\x12SlackConfiguration\x12\x13\n\x0bwebhook_url\x18\x01 \x01(\t\"0\n\x12\x45mailConfiguration\x12\x1a\n\x12recipient_email_id\x18\x01 \x01(\t\"\x89\x02\n\x12NotificationConfig\x12\x39\n\x07\x63hannel\x18\x01 \x01(\x0e\x32(.protos.event.NotificationConfig.Channel\x12?\n\x13slack_configuration\x18\x02 \x01(\x0b\x32 .protos.event.SlackConfigurationH\x00\x12?\n\x13\x65mail_configuration\x18\x03 \x01(\x0b\x32 .protos.event.EmailConfigurationH\x00\",\n\x07\x43hannel\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05SLACK\x10\x01\x12\t\n\x05\x45MAIL\x10\x02\x42\x08\n\x06\x63onfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.event.notification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLACKCONFIGURATION._serialized_start=49
  _SLACKCONFIGURATION._serialized_end=90
  _EMAILCONFIGURATION._serialized_start=92
  _EMAILCONFIGURATION._serialized_end=140
  _NOTIFICATIONCONFIG._serialized_start=143
  _NOTIFICATIONCONFIG._serialized_end=408
  _NOTIFICATIONCONFIG_CHANNEL._serialized_start=354
  _NOTIFICATIONCONFIG_CHANNEL._serialized_end=398
# @@protoc_insertion_point(module_scope)
