# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/event/search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.event import base_pb2 as protos_dot_event_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/event/search.proto\x12\x0cprotos.event\x1a\x17protos/event/base.proto\"M\n\x12\x46uzzySearchRequest\x12&\n\x07\x63ontext\x18\x01 \x01(\x0e\x32\x15.protos.event.Context\x12\x0f\n\x07pattern\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.event.search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FUZZYSEARCHREQUEST._serialized_start=68
  _FUZZYSEARCHREQUEST._serialized_end=145
# @@protoc_insertion_point(module_scope)
