"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import protos.event.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class FuzzySearchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    PATTERN_FIELD_NUMBER: builtins.int
    context: protos.event.base_pb2.Context.ValueType
    pattern: builtins.str
    def __init__(
        self,
        *,
        context: protos.event.base_pb2.Context.ValueType = ...,
        pattern: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["context", b"context", "pattern", b"pattern"]) -> None: ...

global___FuzzySearchRequest = FuzzySearchRequest
