"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.wrappers_pb2
import protos.event.literal_pb2
import protos.event.query_base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RegexEventProcessingFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGULAR_EXPRESSIONS_FIELD_NUMBER: builtins.int
    @property
    def regular_expressions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        regular_expressions: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["regular_expressions", b"regular_expressions"]) -> None: ...

global___RegexEventProcessingFilter = RegexEventProcessingFilter

@typing_extensions.final
class JSONEventProcessingFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class JSONFilter(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        PATH_FIELD_NUMBER: builtins.int
        OP_FIELD_NUMBER: builtins.int
        LITERAL_FIELD_NUMBER: builtins.int
        key: builtins.str
        path: builtins.str
        op: protos.event.query_base_pb2.Op.ValueType
        @property
        def literal(self) -> protos.event.literal_pb2.Literal: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            path: builtins.str = ...,
            op: protos.event.query_base_pb2.Op.ValueType = ...,
            literal: protos.event.literal_pb2.Literal | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["literal", b"literal"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "literal", b"literal", "op", b"op", "path", b"path"]) -> None: ...

    FILTERS_FIELD_NUMBER: builtins.int
    @property
    def filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___JSONEventProcessingFilter.JSONFilter]: ...
    def __init__(
        self,
        *,
        filters: collections.abc.Iterable[global___JSONEventProcessingFilter.JSONFilter] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filters", b"filters"]) -> None: ...

global___JSONEventProcessingFilter = JSONEventProcessingFilter

@typing_extensions.final
class GrokEventProcessingParser(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GROK_EXPRESSION_FIELD_NUMBER: builtins.int
    @property
    def grok_expression(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        grok_expression: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["grok_expression", b"grok_expression"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["grok_expression", b"grok_expression"]) -> None: ...

global___GrokEventProcessingParser = GrokEventProcessingParser

@typing_extensions.final
class EventProcessingFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EventProcessingFilter._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEFAULT: EventProcessingFilter._Type.ValueType  # 0
        REGEX: EventProcessingFilter._Type.ValueType  # 1
        JSON_FIELD: EventProcessingFilter._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    DEFAULT: EventProcessingFilter.Type.ValueType  # 0
    REGEX: EventProcessingFilter.Type.ValueType  # 1
    JSON_FIELD: EventProcessingFilter.Type.ValueType  # 2

    @typing_extensions.final
    class Stats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOTAL_EVENT_COUNT_FIELD_NUMBER: builtins.int
        TOTAL_FILTERED_EVENT_COUNT_FIELD_NUMBER: builtins.int
        TOTAL_FILTERED_FAILED_EVENT_COUNT_FIELD_NUMBER: builtins.int
        TOTAL_GENERATED_DRD_EVENT_COUNT_FIELD_NUMBER: builtins.int
        @property
        def total_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_filtered_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_filtered_failed_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_generated_drd_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        def __init__(
            self,
            *,
            total_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_filtered_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_filtered_failed_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_generated_drd_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["total_event_count", b"total_event_count", "total_filtered_event_count", b"total_filtered_event_count", "total_filtered_failed_event_count", b"total_filtered_failed_event_count", "total_generated_drd_event_count", b"total_generated_drd_event_count"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["total_event_count", b"total_event_count", "total_filtered_event_count", b"total_filtered_event_count", "total_filtered_failed_event_count", b"total_filtered_failed_event_count", "total_generated_drd_event_count", b"total_generated_drd_event_count"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    REGEX_FIELD_NUMBER: builtins.int
    JSON_FIELD_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    type: global___EventProcessingFilter.Type.ValueType
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    created_at: builtins.int
    @property
    def stats(self) -> global___EventProcessingFilter.Stats: ...
    @property
    def regex(self) -> global___RegexEventProcessingFilter: ...
    @property
    def json_field(self) -> global___JSONEventProcessingFilter: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        type: global___EventProcessingFilter.Type.ValueType = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        created_at: builtins.int = ...,
        stats: global___EventProcessingFilter.Stats | None = ...,
        regex: global___RegexEventProcessingFilter | None = ...,
        json_field: global___JSONEventProcessingFilter | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["filter", b"filter", "id", b"id", "is_active", b"is_active", "json_field", b"json_field", "name", b"name", "regex", b"regex", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "filter", b"filter", "id", b"id", "is_active", b"is_active", "json_field", b"json_field", "name", b"name", "regex", b"regex", "stats", b"stats", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["filter", b"filter"]) -> typing_extensions.Literal["regex", "json_field"] | None: ...

global___EventProcessingFilter = EventProcessingFilter

@typing_extensions.final
class UpdateEventProcessingFilterOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateEventProcessingFilterOp._Op.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateEventProcessingFilterOp._Op.ValueType  # 0
        UPDATE_EVENT_PROCESSING_FILTER_NAME: UpdateEventProcessingFilterOp._Op.ValueType  # 1
        UPDATE_EVENT_PROCESSING_FILTER_STATUS: UpdateEventProcessingFilterOp._Op.ValueType  # 2

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateEventProcessingFilterOp.Op.ValueType  # 0
    UPDATE_EVENT_PROCESSING_FILTER_NAME: UpdateEventProcessingFilterOp.Op.ValueType  # 1
    UPDATE_EVENT_PROCESSING_FILTER_STATUS: UpdateEventProcessingFilterOp.Op.ValueType  # 2

    @typing_extensions.final
    class UpdateEventProcessingFilterName(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

    @typing_extensions.final
    class UpdateEventProcessingFilterStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_EVENT_PROCESSING_FILTER_NAME_FIELD_NUMBER: builtins.int
    UPDATE_EVENT_PROCESSING_FILTER_STATUS_FIELD_NUMBER: builtins.int
    op: global___UpdateEventProcessingFilterOp.Op.ValueType
    @property
    def update_event_processing_filter_name(self) -> global___UpdateEventProcessingFilterOp.UpdateEventProcessingFilterName: ...
    @property
    def update_event_processing_filter_status(self) -> global___UpdateEventProcessingFilterOp.UpdateEventProcessingFilterStatus: ...
    def __init__(
        self,
        *,
        op: global___UpdateEventProcessingFilterOp.Op.ValueType = ...,
        update_event_processing_filter_name: global___UpdateEventProcessingFilterOp.UpdateEventProcessingFilterName | None = ...,
        update_event_processing_filter_status: global___UpdateEventProcessingFilterOp.UpdateEventProcessingFilterStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update", b"update", "update_event_processing_filter_name", b"update_event_processing_filter_name", "update_event_processing_filter_status", b"update_event_processing_filter_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["op", b"op", "update", b"update", "update_event_processing_filter_name", b"update_event_processing_filter_name", "update_event_processing_filter_status", b"update_event_processing_filter_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["update", b"update"]) -> typing_extensions.Literal["update_event_processing_filter_name", "update_event_processing_filter_status"] | None: ...

global___UpdateEventProcessingFilterOp = UpdateEventProcessingFilterOp

@typing_extensions.final
class EventProcessingParser(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EventProcessingParser._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEFAULT: EventProcessingParser._Type.ValueType  # 0
        GROK: EventProcessingParser._Type.ValueType  # 1

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    DEFAULT: EventProcessingParser.Type.ValueType  # 0
    GROK: EventProcessingParser.Type.ValueType  # 1

    @typing_extensions.final
    class ParsedDrdEventDefinition(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        EVENT_TIMESTAMP_FIELD_FIELD_NUMBER: builtins.int
        EVENT_NAME_FIELD_FIELD_NUMBER: builtins.int
        CUSTOM_EVENT_NAME_FIELD_NUMBER: builtins.int
        @property
        def event_timestamp_field(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def event_name_field(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def custom_event_name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            event_timestamp_field: google.protobuf.wrappers_pb2.StringValue | None = ...,
            event_name_field: google.protobuf.wrappers_pb2.StringValue | None = ...,
            custom_event_name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["custom_event_name", b"custom_event_name", "event_name", b"event_name", "event_name_field", b"event_name_field", "event_timestamp_field", b"event_timestamp_field"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["custom_event_name", b"custom_event_name", "event_name", b"event_name", "event_name_field", b"event_name_field", "event_timestamp_field", b"event_timestamp_field"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["event_name", b"event_name"]) -> typing_extensions.Literal["event_name_field", "custom_event_name"] | None: ...

    @typing_extensions.final
    class Stats(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOTAL_PARSED_EVENT_COUNT_FIELD_NUMBER: builtins.int
        TOTAL_PARSER_FAILED_EVENT_COUNT_FIELD_NUMBER: builtins.int
        TOTAL_PARSED_EVENT_KEYS_FIELD_NUMBER: builtins.int
        TOTAL_GENERATED_DRD_EVENT_COUNT_FIELD_NUMBER: builtins.int
        PARSED_EVENT_KEYS_FIELD_NUMBER: builtins.int
        PARSED_TIMESTAMP_KEYS_FIELD_NUMBER: builtins.int
        PARSED_KEYS_FREQUENCY_FIELD_NUMBER: builtins.int
        @property
        def total_parsed_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_parser_failed_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_parsed_event_keys(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def total_generated_drd_event_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def parsed_event_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        @property
        def parsed_timestamp_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        @property
        def parsed_keys_frequency(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.struct_pb2.Struct]: ...
        def __init__(
            self,
            *,
            total_parsed_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_parser_failed_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_parsed_event_keys: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            total_generated_drd_event_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            parsed_event_keys: collections.abc.Iterable[builtins.str] | None = ...,
            parsed_timestamp_keys: collections.abc.Iterable[builtins.str] | None = ...,
            parsed_keys_frequency: collections.abc.Iterable[google.protobuf.struct_pb2.Struct] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["total_generated_drd_event_count", b"total_generated_drd_event_count", "total_parsed_event_count", b"total_parsed_event_count", "total_parsed_event_keys", b"total_parsed_event_keys", "total_parser_failed_event_count", b"total_parser_failed_event_count"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["parsed_event_keys", b"parsed_event_keys", "parsed_keys_frequency", b"parsed_keys_frequency", "parsed_timestamp_keys", b"parsed_timestamp_keys", "total_generated_drd_event_count", b"total_generated_drd_event_count", "total_parsed_event_count", b"total_parsed_event_count", "total_parsed_event_keys", b"total_parsed_event_keys", "total_parser_failed_event_count", b"total_parser_failed_event_count"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    DRD_EVENT_DEFINITION_RULE_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    GROK_PARSER_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    type: global___EventProcessingParser.Type.ValueType
    @property
    def filter(self) -> global___EventProcessingFilter: ...
    @property
    def drd_event_definition_rule(self) -> global___EventProcessingParser.ParsedDrdEventDefinition: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    created_at: builtins.int
    @property
    def stats(self) -> global___EventProcessingParser.Stats: ...
    @property
    def grok_parser(self) -> global___GrokEventProcessingParser: ...
    def __init__(
        self,
        *,
        id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        type: global___EventProcessingParser.Type.ValueType = ...,
        filter: global___EventProcessingFilter | None = ...,
        drd_event_definition_rule: global___EventProcessingParser.ParsedDrdEventDefinition | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        created_at: builtins.int = ...,
        stats: global___EventProcessingParser.Stats | None = ...,
        grok_parser: global___GrokEventProcessingParser | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["drd_event_definition_rule", b"drd_event_definition_rule", "filter", b"filter", "grok_parser", b"grok_parser", "id", b"id", "is_active", b"is_active", "name", b"name", "parser", b"parser", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "drd_event_definition_rule", b"drd_event_definition_rule", "filter", b"filter", "grok_parser", b"grok_parser", "id", b"id", "is_active", b"is_active", "name", b"name", "parser", b"parser", "stats", b"stats", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["parser", b"parser"]) -> typing_extensions.Literal["grok_parser"] | None: ...

global___EventProcessingParser = EventProcessingParser

@typing_extensions.final
class UpdateEventProcessingParserOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateEventProcessingParserOp._Op.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateEventProcessingParserOp._Op.ValueType  # 0
        UPDATE_EVENT_PROCESSING_PARSER_NAME: UpdateEventProcessingParserOp._Op.ValueType  # 1
        UPDATE_EVENT_PROCESSING_PARSER_STATUS: UpdateEventProcessingParserOp._Op.ValueType  # 2

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateEventProcessingParserOp.Op.ValueType  # 0
    UPDATE_EVENT_PROCESSING_PARSER_NAME: UpdateEventProcessingParserOp.Op.ValueType  # 1
    UPDATE_EVENT_PROCESSING_PARSER_STATUS: UpdateEventProcessingParserOp.Op.ValueType  # 2

    @typing_extensions.final
    class UpdateEventProcessingParserName(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

    @typing_extensions.final
    class UpdateEventProcessingParserStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_EVENT_PROCESSING_PARSER_NAME_FIELD_NUMBER: builtins.int
    UPDATE_EVENT_PROCESSING_PARSER_STATUS_FIELD_NUMBER: builtins.int
    op: global___UpdateEventProcessingParserOp.Op.ValueType
    @property
    def update_event_processing_parser_name(self) -> global___UpdateEventProcessingParserOp.UpdateEventProcessingParserName: ...
    @property
    def update_event_processing_parser_status(self) -> global___UpdateEventProcessingParserOp.UpdateEventProcessingParserStatus: ...
    def __init__(
        self,
        *,
        op: global___UpdateEventProcessingParserOp.Op.ValueType = ...,
        update_event_processing_parser_name: global___UpdateEventProcessingParserOp.UpdateEventProcessingParserName | None = ...,
        update_event_processing_parser_status: global___UpdateEventProcessingParserOp.UpdateEventProcessingParserStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update", b"update", "update_event_processing_parser_name", b"update_event_processing_parser_name", "update_event_processing_parser_status", b"update_event_processing_parser_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["op", b"op", "update", b"update", "update_event_processing_parser_name", b"update_event_processing_parser_name", "update_event_processing_parser_status", b"update_event_processing_parser_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["update", b"update"]) -> typing_extensions.Literal["update_event_processing_parser_name", "update_event_processing_parser_status"] | None: ...

global___UpdateEventProcessingParserOp = UpdateEventProcessingParserOp
