"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.event.alert_pb2
import protos.event.base_pb2
import protos.event.monitor_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EntityInstanceTimelineRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class MonitorTransactionEventTypeMapping(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MONITOR_TRANSACTION_FIELD_NUMBER: builtins.int
        TRANSACTION_EVENT_TYPE_FIELD_NUMBER: builtins.int
        HAS_ALERTS_FIELD_NUMBER: builtins.int
        @property
        def monitor_transaction(self) -> protos.event.monitor_pb2.MonitorTransactionPartial: ...
        transaction_event_type: protos.event.monitor_pb2.MonitorTransaction.MonitorTransactionEventType.ValueType
        @property
        def has_alerts(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            monitor_transaction: protos.event.monitor_pb2.MonitorTransactionPartial | None = ...,
            transaction_event_type: protos.event.monitor_pb2.MonitorTransaction.MonitorTransactionEventType.ValueType = ...,
            has_alerts: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["has_alerts", b"has_alerts", "monitor_transaction", b"monitor_transaction"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["has_alerts", b"has_alerts", "monitor_transaction", b"monitor_transaction", "transaction_event_type", b"transaction_event_type"]) -> None: ...

    TIMESTAMP_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    TRANSACTION_EVENT_TYPE_MAPPING_FIELD_NUMBER: builtins.int
    ALERTS_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    @property
    def event(self) -> protos.event.base_pb2.Event: ...
    @property
    def transaction_event_type_mapping(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityInstanceTimelineRecord.MonitorTransactionEventTypeMapping]: ...
    @property
    def alerts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.alert_pb2.AlertMonitorTransaction]: ...
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        event: protos.event.base_pb2.Event | None = ...,
        transaction_event_type_mapping: collections.abc.Iterable[global___EntityInstanceTimelineRecord.MonitorTransactionEventTypeMapping] | None = ...,
        alerts: collections.abc.Iterable[protos.event.alert_pb2.AlertMonitorTransaction] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event", b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alerts", b"alerts", "event", b"event", "timestamp", b"timestamp", "transaction_event_type_mapping", b"transaction_event_type_mapping"]) -> None: ...

global___EntityInstanceTimelineRecord = EntityInstanceTimelineRecord
