"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import protos.event.entity_pb2
import protos.event.literal_pb2
import protos.event.monitor_pb2
import protos.event.notification_pb2
import protos.event.query_base_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TriggerPriority:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TriggerPriorityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TriggerPriority.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN_P: _TriggerPriority.ValueType  # 0
    TP_0: _TriggerPriority.ValueType  # 1
    TP_1: _TriggerPriority.ValueType  # 2
    TP_2: _TriggerPriority.ValueType  # 3
    TP_3: _TriggerPriority.ValueType  # 4
    TP_4: _TriggerPriority.ValueType  # 5

class TriggerPriority(_TriggerPriority, metaclass=_TriggerPriorityEnumTypeWrapper): ...

UNKNOWN_P: TriggerPriority.ValueType  # 0
TP_0: TriggerPriority.ValueType  # 1
TP_1: TriggerPriority.ValueType  # 2
TP_2: TriggerPriority.ValueType  # 3
TP_3: TriggerPriority.ValueType  # 4
TP_4: TriggerPriority.ValueType  # 5
global___TriggerPriority = TriggerPriority

@typing_extensions.final
class MissingEventTrigger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSACTION_TIME_THRESHOLD_FIELD_NUMBER: builtins.int
    @property
    def transaction_time_threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    def __init__(
        self,
        *,
        transaction_time_threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["transaction_time_threshold", b"transaction_time_threshold"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["transaction_time_threshold", b"transaction_time_threshold"]) -> None: ...

global___MissingEventTrigger = MissingEventTrigger

@typing_extensions.final
class DelayedEventTrigger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DelayedEventTrigger._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: DelayedEventTrigger._Type.ValueType  # 0
        DELAYED_EVENTS: DelayedEventTrigger._Type.ValueType  # 1
        MISSING_AND_DELAYED_EVENTS: DelayedEventTrigger._Type.ValueType  # 2
        MISSING_EVENTS: DelayedEventTrigger._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: DelayedEventTrigger.Type.ValueType  # 0
    DELAYED_EVENTS: DelayedEventTrigger.Type.ValueType  # 1
    MISSING_AND_DELAYED_EVENTS: DelayedEventTrigger.Type.ValueType  # 2
    MISSING_EVENTS: DelayedEventTrigger.Type.ValueType  # 3

    TRANSACTION_TIME_THRESHOLD_FIELD_NUMBER: builtins.int
    TRIGGER_THRESHOLD_FIELD_NUMBER: builtins.int
    RESOLUTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SKIP_UNFINISHED_TRANSACTIONS_FIELD_NUMBER: builtins.int
    @property
    def transaction_time_threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def trigger_threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def resolution(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    type: global___DelayedEventTrigger.Type.ValueType
    @property
    def skip_unfinished_transactions(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        transaction_time_threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        trigger_threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        resolution: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
        type: global___DelayedEventTrigger.Type.ValueType = ...,
        skip_unfinished_transactions: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resolution", b"resolution", "skip_unfinished_transactions", b"skip_unfinished_transactions", "transaction_time_threshold", b"transaction_time_threshold", "trigger_threshold", b"trigger_threshold"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resolution", b"resolution", "skip_unfinished_transactions", b"skip_unfinished_transactions", "transaction_time_threshold", b"transaction_time_threshold", "trigger_threshold", b"trigger_threshold", "type", b"type"]) -> None: ...

global___DelayedEventTrigger = DelayedEventTrigger

@typing_extensions.final
class DelayedEventTriggerOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRANSACTION_TIME_THRESHOLD_FIELD_NUMBER: builtins.int
    TRIGGER_THRESHOLD_FIELD_NUMBER: builtins.int
    RESOLUTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def transaction_time_threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def trigger_threshold(self) -> google.protobuf.wrappers_pb2.DoubleValue: ...
    @property
    def resolution(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    @property
    def type(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DelayedEventTrigger.Type.ValueType]: ...
    def __init__(
        self,
        *,
        transaction_time_threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        trigger_threshold: google.protobuf.wrappers_pb2.DoubleValue | None = ...,
        resolution: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
        type: collections.abc.Iterable[global___DelayedEventTrigger.Type.ValueType] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["resolution", b"resolution", "transaction_time_threshold", b"transaction_time_threshold", "trigger_threshold", b"trigger_threshold"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resolution", b"resolution", "transaction_time_threshold", b"transaction_time_threshold", "trigger_threshold", b"trigger_threshold", "type", b"type"]) -> None: ...

global___DelayedEventTriggerOptions = DelayedEventTriggerOptions

@typing_extensions.final
class TriggerStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LAST_TRIGGERED_AT_FIELD_NUMBER: builtins.int
    ALERT_COUNT_FIELD_NUMBER: builtins.int
    @property
    def last_triggered_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def alert_count(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    def __init__(
        self,
        *,
        last_triggered_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        alert_count: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["alert_count", b"alert_count", "last_triggered_at", b"last_triggered_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["alert_count", b"alert_count", "last_triggered_at", b"last_triggered_at"]) -> None: ...

global___TriggerStats = TriggerStats

@typing_extensions.final
class TriggerDefinition(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TriggerDefinition._Type.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: TriggerDefinition._Type.ValueType  # 0
        MISSING_EVENT: TriggerDefinition._Type.ValueType  # 1
        DELAYED_EVENT: TriggerDefinition._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    UNKNOWN: TriggerDefinition.Type.ValueType  # 0
    MISSING_EVENT: TriggerDefinition.Type.ValueType  # 1
    DELAYED_EVENT: TriggerDefinition.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    MISSING_EVENT_TRIGGER_FIELD_NUMBER: builtins.int
    DELAYED_EVENT_TRIGGER_FIELD_NUMBER: builtins.int
    PRIMARY_EVENT_FILTERS_FIELD_NUMBER: builtins.int
    SECONDARY_EVENT_FILTERS_FIELD_NUMBER: builtins.int
    type: global___TriggerDefinition.Type.ValueType
    @property
    def missing_event_trigger(self) -> global___MissingEventTrigger: ...
    @property
    def delayed_event_trigger(self) -> global___DelayedEventTrigger: ...
    @property
    def primary_event_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BasicTriggerFilter]: ...
    @property
    def secondary_event_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BasicTriggerFilter]: ...
    def __init__(
        self,
        *,
        type: global___TriggerDefinition.Type.ValueType = ...,
        missing_event_trigger: global___MissingEventTrigger | None = ...,
        delayed_event_trigger: global___DelayedEventTrigger | None = ...,
        primary_event_filters: collections.abc.Iterable[global___BasicTriggerFilter] | None = ...,
        secondary_event_filters: collections.abc.Iterable[global___BasicTriggerFilter] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delayed_event_trigger", b"delayed_event_trigger", "missing_event_trigger", b"missing_event_trigger", "trigger", b"trigger"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["delayed_event_trigger", b"delayed_event_trigger", "missing_event_trigger", b"missing_event_trigger", "primary_event_filters", b"primary_event_filters", "secondary_event_filters", b"secondary_event_filters", "trigger", b"trigger", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["trigger", b"trigger"]) -> typing_extensions.Literal["missing_event_trigger", "delayed_event_trigger"] | None: ...

global___TriggerDefinition = TriggerDefinition

@typing_extensions.final
class Trigger(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    MONITOR_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    STATS_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    @property
    def monitor(self) -> protos.event.monitor_pb2.Monitor: ...
    priority: global___TriggerPriority.ValueType
    @property
    def definition(self) -> global___TriggerDefinition: ...
    @property
    def stats(self) -> global___TriggerStats: ...
    @property
    def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        monitor: protos.event.monitor_pb2.Monitor | None = ...,
        priority: global___TriggerPriority.ValueType = ...,
        definition: global___TriggerDefinition | None = ...,
        stats: global___TriggerStats | None = ...,
        is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["definition", b"definition", "is_active", b"is_active", "monitor", b"monitor", "stats", b"stats"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["definition", b"definition", "id", b"id", "is_active", b"is_active", "monitor", b"monitor", "name", b"name", "priority", b"priority", "stats", b"stats"]) -> None: ...

global___Trigger = Trigger

@typing_extensions.final
class TriggerSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    MONITOR_DETAILS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    type: global___TriggerDefinition.Type.ValueType
    @property
    def monitor_details(self) -> protos.event.monitor_pb2.MonitorEventTypeDetails: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        type: global___TriggerDefinition.Type.ValueType = ...,
        monitor_details: protos.event.monitor_pb2.MonitorEventTypeDetails | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["monitor_details", b"monitor_details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "monitor_details", b"monitor_details", "name", b"name", "type", b"type"]) -> None: ...

global___TriggerSummary = TriggerSummary

@typing_extensions.final
class BasicTriggerFilter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_KEY_ID_FIELD_NUMBER: builtins.int
    OP_FIELD_NUMBER: builtins.int
    LITERAL_FIELD_NUMBER: builtins.int
    event_key_id: builtins.int
    op: protos.event.query_base_pb2.Op.ValueType
    @property
    def literal(self) -> protos.event.literal_pb2.Literal: ...
    def __init__(
        self,
        *,
        event_key_id: builtins.int = ...,
        op: protos.event.query_base_pb2.Op.ValueType = ...,
        literal: protos.event.literal_pb2.Literal | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["literal", b"literal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_key_id", b"event_key_id", "literal", b"literal", "op", b"op"]) -> None: ...

global___BasicTriggerFilter = BasicTriggerFilter

@typing_extensions.final
class BasicTriggerFilterOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OP_DESCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def op_description(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.query_base_pb2.OpDescription]: ...
    def __init__(
        self,
        *,
        op_description: collections.abc.Iterable[protos.event.query_base_pb2.OpDescription] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["op_description", b"op_description"]) -> None: ...

global___BasicTriggerFilterOptions = BasicTriggerFilterOptions

@typing_extensions.final
class MonitorTriggerNotificationDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRIGGER_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    @property
    def trigger(self) -> global___Trigger: ...
    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.notification_pb2.NotificationConfig]: ...
    def __init__(
        self,
        *,
        trigger: global___Trigger | None = ...,
        notifications: collections.abc.Iterable[protos.event.notification_pb2.NotificationConfig] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["trigger", b"trigger"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["notifications", b"notifications", "trigger", b"trigger"]) -> None: ...

global___MonitorTriggerNotificationDetail = MonitorTriggerNotificationDetail

@typing_extensions.final
class EntityTriggerNotificationDetail(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRIGGER_FIELD_NUMBER: builtins.int
    NOTIFICATIONS_FIELD_NUMBER: builtins.int
    @property
    def trigger(self) -> protos.event.entity_pb2.EntityTrigger: ...
    @property
    def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.notification_pb2.NotificationConfig]: ...
    def __init__(
        self,
        *,
        trigger: protos.event.entity_pb2.EntityTrigger | None = ...,
        notifications: collections.abc.Iterable[protos.event.notification_pb2.NotificationConfig] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["trigger", b"trigger"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["notifications", b"notifications", "trigger", b"trigger"]) -> None: ...

global___EntityTriggerNotificationDetail = EntityTriggerNotificationDetail

@typing_extensions.final
class UpdateTriggerOp(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Op:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _OpEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UpdateTriggerOp._Op.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: UpdateTriggerOp._Op.ValueType  # 0
        UPDATE_TRIGGER_NAME: UpdateTriggerOp._Op.ValueType  # 1
        UPDATE_TRIGGER_STATUS: UpdateTriggerOp._Op.ValueType  # 2
        UPDATE_TRIGGER_PRIORITY: UpdateTriggerOp._Op.ValueType  # 3
        UPDATE_TRIGGER_DEFINITION: UpdateTriggerOp._Op.ValueType  # 4
        UPDATE_TRIGGER_NOTIFICATIONS: UpdateTriggerOp._Op.ValueType  # 5

    class Op(_Op, metaclass=_OpEnumTypeWrapper): ...
    UNKNOWN: UpdateTriggerOp.Op.ValueType  # 0
    UPDATE_TRIGGER_NAME: UpdateTriggerOp.Op.ValueType  # 1
    UPDATE_TRIGGER_STATUS: UpdateTriggerOp.Op.ValueType  # 2
    UPDATE_TRIGGER_PRIORITY: UpdateTriggerOp.Op.ValueType  # 3
    UPDATE_TRIGGER_DEFINITION: UpdateTriggerOp.Op.ValueType  # 4
    UPDATE_TRIGGER_NOTIFICATIONS: UpdateTriggerOp.Op.ValueType  # 5

    @typing_extensions.final
    class UpdateTriggerName(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        @property
        def name(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            name: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["name", b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

    @typing_extensions.final
    class UpdateTriggerStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: builtins.int
        @property
        def is_active(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            is_active: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["is_active", b"is_active"]) -> None: ...

    @typing_extensions.final
    class UpdateTriggerPriority(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRIORITY_FIELD_NUMBER: builtins.int
        priority: global___TriggerPriority.ValueType
        def __init__(
            self,
            *,
            priority: global___TriggerPriority.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["priority", b"priority"]) -> None: ...

    @typing_extensions.final
    class UpdateTriggerDefinition(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DEFINITION_FIELD_NUMBER: builtins.int
        @property
        def definition(self) -> global___TriggerDefinition: ...
        def __init__(
            self,
            *,
            definition: global___TriggerDefinition | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["definition", b"definition"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["definition", b"definition"]) -> None: ...

    @typing_extensions.final
    class UpdateTriggerNotifications(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NOTIFICATIONS_FIELD_NUMBER: builtins.int
        @property
        def notifications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.event.notification_pb2.NotificationConfig]: ...
        def __init__(
            self,
            *,
            notifications: collections.abc.Iterable[protos.event.notification_pb2.NotificationConfig] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["notifications", b"notifications"]) -> None: ...

    OP_FIELD_NUMBER: builtins.int
    UPDATE_TRIGGER_NAME_FIELD_NUMBER: builtins.int
    UPDATE_TRIGGER_STATUS_FIELD_NUMBER: builtins.int
    UPDATE_TRIGGER_PRIORITY_FIELD_NUMBER: builtins.int
    UPDATE_TRIGGER_DEFINITION_FIELD_NUMBER: builtins.int
    UPDATE_TRIGGER_NOTIFICATIONS_FIELD_NUMBER: builtins.int
    op: global___UpdateTriggerOp.Op.ValueType
    @property
    def update_trigger_name(self) -> global___UpdateTriggerOp.UpdateTriggerName: ...
    @property
    def update_trigger_status(self) -> global___UpdateTriggerOp.UpdateTriggerStatus: ...
    @property
    def update_trigger_priority(self) -> global___UpdateTriggerOp.UpdateTriggerPriority: ...
    @property
    def update_trigger_definition(self) -> global___UpdateTriggerOp.UpdateTriggerDefinition: ...
    @property
    def update_trigger_notifications(self) -> global___UpdateTriggerOp.UpdateTriggerNotifications: ...
    def __init__(
        self,
        *,
        op: global___UpdateTriggerOp.Op.ValueType = ...,
        update_trigger_name: global___UpdateTriggerOp.UpdateTriggerName | None = ...,
        update_trigger_status: global___UpdateTriggerOp.UpdateTriggerStatus | None = ...,
        update_trigger_priority: global___UpdateTriggerOp.UpdateTriggerPriority | None = ...,
        update_trigger_definition: global___UpdateTriggerOp.UpdateTriggerDefinition | None = ...,
        update_trigger_notifications: global___UpdateTriggerOp.UpdateTriggerNotifications | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update", b"update", "update_trigger_definition", b"update_trigger_definition", "update_trigger_name", b"update_trigger_name", "update_trigger_notifications", b"update_trigger_notifications", "update_trigger_priority", b"update_trigger_priority", "update_trigger_status", b"update_trigger_status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["op", b"op", "update", b"update", "update_trigger_definition", b"update_trigger_definition", "update_trigger_name", b"update_trigger_name", "update_trigger_notifications", b"update_trigger_notifications", "update_trigger_priority", b"update_trigger_priority", "update_trigger_status", b"update_trigger_status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["update", b"update"]) -> typing_extensions.Literal["update_trigger_name", "update_trigger_status", "update_trigger_priority", "update_trigger_definition", "update_trigger_notifications"] | None: ...

global___UpdateTriggerOp = UpdateTriggerOp
