# Generated by Django 4.1.10 on 2023-12-03 11:06

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_is_whitelisted'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='result',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SUCCESS'), (2, 'FAILURE')], db_index=True, default=management.models.PeriodicTaskResult['UNKNOWN'], null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SKIPPED'), (2, 'SCHEDULED'), (3, 'RUNNING'), (4, 'COMPLETED'), (5, 'FAILED')], db_index=True, default=management.models.PeriodicTaskStatus['UNKNOWN'], null=True),
        ),
    ]
