{{- if .Values.envRenderSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prototype.fullname" . }}-db
  labels:
    {{- include "prototype.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.envRenderSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
