# Generated by Django 4.1.10 on 2023-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_alter_connectorkey_key_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformermapping',
            name='transformer_type',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN_TT'), (2, 'SEGMENT_DFAULT_TRANSFORMER'), (3, 'AMPLITUDE_DEFAULT_TRANSFORMER'), (4, 'CLOUDWATCH_JSON_LOG_TRANSFORMER')], default=0, null=True),
        ),
    ]
