# Generated by Django 4.1.10 on 2023-12-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_is_whitelisted'),
        ('connectors', '0005_alter_transformermapping_transformer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProcessingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'DEFAULT'), (1, 'REGEX'), (2, 'JSON_FIELD')], default=0, null=True)),
                ('filter', models.JSONField(blank=True, null=True)),
                ('filter_md5', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'type', 'filter_md5')},
            },
        ),
        migrations.CreateModel(
            name='EventProcessingParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'DEFAULT'), (1, 'GROK')], default=0, null=True)),
                ('parser', models.JSONField(blank=True, db_index=True, null=True)),
                ('parser_md5', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('drd_event_definition_rule', models.JSONField(blank=True, db_index=True, null=True)),
                ('drd_event_definition_rule_md5', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.eventprocessingfilter')),
            ],
            options={
                'unique_together': {('account', 'type', 'filter', 'parser_md5', 'drd_event_definition_rule_md5')},
            },
        ),
    ]
