{{- if not (lookup "v1" "Secret" .Release.Namespace (include "aws.secret.name" .)) -}}
{{- if .Values.aws.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "aws.secret.name" .) }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.aws.accessKeyId | b64enc }}
  secretAccessKey: {{ .Values.aws.secretAccessKey | b64enc }}
{{- end }}
{{- end }}
