{{- if not (lookup "v1" "Secret" .Release.Namespace (include "key.secret.name" .)) -}}
{{- if .Values.key.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "key.secret.name" .) }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ .Values.key.key }}
{{- end }}
{{- end }}
