{{- if not (lookup "v1" "Secret" .Release.Namespace (include "db.secret.name" .)) -}}
{{- if .Values.db.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "db.secret.name" .) }}
  labels:
    {{- include "secrets.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
{{- end }}
{{- end }}
