apiVersion: v1
kind: Service
metadata:
  name: {{ include "webvault.fullname" . }}
  labels:
    {{- include "webvault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "webvault.selectorLabels" . | nindent 4 }}
