# Generated by Django 4.1.4 on 2023-02-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_org_user_org_alter_user_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to='accounts.org')),
            ],
            options={
                'verbose_name': 'ApiToken',
                'verbose_name_plural': 'ApiTokens',
            },
        ),
    ]
