# Generated by Django 4.1.4 on 2023-02-27 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_accountapitoken_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_account', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
