# Generated by Django 4.1.4 on 2023-06-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
