# Generated by Django 4.1.4 on 2023-02-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_account_accountapitoken_alter_user_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'KEY_TYPE_UNKNOWN'), (1, 'KEY_TYPE_STRING'), (2, 'KEY_TYPE_LONG'), (3, 'KEY_TYPE_DOUBLE'), (4, 'KEY_TYPE_BOOLEAN'), (5, 'KEY_TYPE_BYTE'), (6, 'KEY_TYPE_ARRAY'), (7, 'KEY_TYPE_OBJECT')], db_index=True, default=0, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('primary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_key', to='event.eventkey')),
                ('secondary_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_key', to='event.eventkey')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MonitorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.TextField(db_index=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'PRIMARY_RECEIVED'), (2, 'SECONDARY_RECEIVED')], db_index=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.monitor')),
            ],
            options={
                'unique_together': {('account', 'monitor', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.AddField(
            model_name='eventkey',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.JSONField()),
                ('processed_kvs', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=256)),
                ('webhook_url', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'unique_together': {('account',)},
            },
        ),
        migrations.CreateModel(
            name='MonitorTransactionEventMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('monitor_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.monitortransaction')),
            ],
            options={
                'unique_together': {('account', 'event', 'monitor_transaction')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventkey',
            unique_together={('account', 'event_type', 'name')},
        ),
    ]
