# Generated by Django 4.1.4 on 2023-02-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_accountapitoken_alter_user_unique_together_and_more'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('type', models.IntegerField(choices=[(0, 'UNKNOWN_TT'), (1, 'MISSING_EVENT_TT'), (2, 'DELAYED_EVENT_TT')], db_index=True)),
                ('config', models.JSONField()),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'UNKNOWN_P'), (1, 'TP_0'), (2, 'TP_1'), (3, 'TP_2'), (4, 'TP_3'), (5, 'TP_4')], db_index=True, default=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.monitor')),
            ],
            options={
                'unique_together': {('account', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('monitor_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.monitortransaction')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.trigger')),
            ],
            options={
                'unique_together': {('account', 'trigger', 'monitor_transaction')},
            },
        ),
    ]
