# Generated by Django 4.1.4 on 2023-03-02 07:56

from django.db import migrations, models
import prototype.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_event_source_event_is_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='event_sources',
            field=prototype.fields.ChoiceArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SAMPLE'), (2, 'API'), (3, 'SDK')], null=True), default=list, size=None),
        ),
    ]
