# Generated by Django 4.1.4 on 2023-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventtype_event_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='type',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MISSING_EVENT'), (2, 'DELAYED_EVENT')], db_index=True),
        ),
    ]
