# Generated by Django 4.1.4 on 2023-03-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_owner'),
        ('event', '0005_alter_trigger_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'SLACK')], db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('account', 'config')},
        ),
        migrations.CreateModel(
            name='TriggerNotificationConfigMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.notification')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.trigger')),
            ],
            options={
                'unique_together': {('account', 'trigger', 'notification')},
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger',
            field=models.ManyToManyField(related_name='triggers', through='event.TriggerNotificationConfigMapping', to='event.trigger'),
        ),
    ]
