# Generated by Django 4.1.4 on 2023-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_alert_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='stats',
            field=models.JSONField(null=True),
        ),
    ]
