# Generated by Django 4.1.4 on 2023-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alertmonitortransactionmapping_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'SLACK'), (2, 'EMAIL')], db_index=True),
        ),
    ]
