# Generated by Django 4.1.4 on 2023-03-22 10:39

from django.db import migrations

from event.models import Monitor


def set_trigger_generated_choices_status(apps, schema_editor):
    Trigger = apps.get_model("event", "Trigger")

    for trigger in Trigger.objects.all():  # event__event_type_id
        generated_config = {
            'primary_event_filters': {"event__event_type_id": trigger.monitor.primary_key.event_type.id},
            'secondary_event_filters': {"event__event_type_id": trigger.monitor.secondary_key.event_type.id}
        }
        trigger.generated_config = generated_config
        trigger.save(update_fields=['generated_config'])


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0012_trigger_generated_config'),
    ]

    operations = [
        migrations.RunPython(set_trigger_generated_choices_status, migrations.RunPython.noop)
    ]
