# Generated by Django 4.1.4 on 2023-03-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_owner'),
        ('event', '0013_populate_trigger_generated_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTransactionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('monitor_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.monitortransaction')),
            ],
            options={
                'unique_together': {('account', 'monitor_transaction')},
            },
        ),
    ]
