# Generated by Django 4.1.4 on 2023-04-12 12:16

from django.db import migrations

from protos.event.trigger_pb2 import TriggerDefinition


def set_delayed_trigger_config_skip_unfinished_transactions(apps, schema_editor):
    Trigger = apps.get_model("event", "Trigger")

    for trigger in Trigger.objects.filter(type=TriggerDefinition.Type.DELAYED_EVENT):
        config = trigger.config
        if "skip_unfinished_transactions" not in config:
            config["skip_unfinished_transactions"] = True
            trigger.config = config
            trigger.save(update_fields=['config'])


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0014_monitortransactionstats'),
    ]

    operations = [
        migrations.RunPython(set_delayed_trigger_config_skip_unfinished_transactions, migrations.RunPython.noop)
    ]
