# Generated by Django 4.1.4 on 2023-04-17 05:39

from django.db import migrations, models
import prototype.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_populate_delayed_trigger_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortransaction',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='monitortransactioneventmapping',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN_MT_ET'), (1, 'PRIMARY'), (2, 'SECONDARY')], db_index=True, default=0, null=True),
        ),
    ]
