# Generated by Django 4.1.4 on 2023-04-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_owner'),
        ('event', '0018_remove_monitortransaction_event_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='EntityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entity')),
            ],
            options={
                'unique_together': {('account', 'entity', 'instance')},
            },
        ),
        migrations.CreateModel(
            name='EntityEventKeyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entity')),
                ('event_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventkey')),
            ],
            options={
                'unique_together': {('account', 'entity', 'event_key')},
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='event_key',
            field=models.ManyToManyField(related_name='event_keys', through='event.EntityEventKeyMapping', to='event.eventkey'),
        ),
        migrations.CreateModel(
            name='EntityInstanceMonitorTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(db_index=True)),
                ('transaction', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entity')),
                ('entity_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entityinstance')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.monitor')),
                ('monitor_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.monitortransaction')),
            ],
            options={
                'unique_together': {('account', 'entity_instance', 'monitor_transaction')},
            },
        ),
        migrations.CreateModel(
            name='EntityInstanceEventMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.TextField(db_index=True)),
                ('event_processed_kvs', models.JSONField(blank=True, null=True)),
                ('event_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entity')),
                ('entity_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.entityinstance')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('event_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventkey')),
            ],
            options={
                'unique_together': {('account', 'entity_instance', 'event')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('account', 'name')},
        ),
    ]
