# Generated by Django 4.1.4 on 2023-04-25 09:26

from django.db import migrations

from protos.event.trigger_pb2 import TriggerDefinition


def set_delayed_trigger_config_type(apps, schema_editor):
    Trigger = apps.get_model("event", "Trigger")

    for trigger in Trigger.objects.filter(type=TriggerDefinition.Type.DELAYED_EVENT):
        config = trigger.config
        if "skip_unfinished_transactions" in config:
            config.pop("skip_unfinished_transactions")
        if "type" not in config:
            config["type"] = "DELAYED_EVENTS"
        trigger.config = config
        trigger.save(update_fields=['config'])


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0019_entity_entityinstance_entityeventkeymapping_and_more'),
    ]

    operations = [
        migrations.RunPython(set_delayed_trigger_config_type, migrations.RunPython.noop)
    ]
