# Generated by Django 4.1.4 on 2023-04-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_modify_delayed_event_trigger_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='event_key',
            field=models.ManyToManyField(related_name='entity_event_keys', through='event.EntityEventKeyMapping', to='event.eventkey'),
        ),
    ]
