# Generated by Django 4.1.4 on 2023-05-09 09:54

from django.db import migrations, models
import prototype.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_entity_event_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_source',
            field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SAMPLE'), (2, 'API'), (3, 'SDK'), (4, 'SEGMENT'), (5, 'AMPLITUDE'), (6, 'SNS')], db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='event_sources',
            field=prototype.fields.ChoiceArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'UNKNOWN'), (1, 'SAMPLE'), (2, 'API'), (3, 'SDK'), (4, 'SEGMENT'), (5, 'AMPLITUDE'), (6, 'SNS')], null=True), default=list, size=None),
        ),
    ]
