# Generated by Django 4.1.4 on 2023-09-08 12:59

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import prototype.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_is_whitelisted"),
        ("event", "0023_auto_20230612_1130"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "UNKNOWN"),
                            (1, "LAST_EVENT"),
                            (2, "EVENT_COUNT"),
                        ],
                        db_index=True,
                    ),
                ),
                ("config", models.JSONField()),
                ("generated_config", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.entity",
                    ),
                ),
            ],
        ),
    ]
