# Generated by Django 4.1.4 on 2023-09-11 14:58

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion
import prototype.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_is_whitelisted"),
        ("event", "0026_events_alert_entity_trigger_alter_alert_trigger_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTriggerNotificationConfigMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "entity_trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.entitytrigger",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.notification",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "entity_trigger", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_trigger",
            field=models.ManyToManyField(
                related_name="entity_triggers",
                through="event.EntityTriggerNotificationConfigMapping",
                to="event.entitytrigger",
            ),
        ),
    ]
