# Generated by Django 4.1.4 on 2023-10-06 03:43

import clickhouse_backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_is_whitelisted"),
        ("event", "0028_events_alter_entity_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertEntityInstanceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "UNKNOWN"),
                            (1, "PER_EVENT"),
                            (2, "AGGREGATED_EVENTS"),
                        ],
                        db_index=True,
                        default=0,
                        null=True,
                    ),
                ),
                ("stats", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.alert"
                    ),
                ),
                (
                    "entity_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.entityinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "alert", "entity_instance")},
            },
        ),
        migrations.AddField(
            model_name="entityinstance",
            name="alert",
            field=models.ManyToManyField(
                related_name="entity_alerts",
                through="event.AlertEntityInstanceMapping",
                to="event.alert",
            ),
        ),
    ]
