apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingest.fullname" . }}
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ingest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ingest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "{{ .Values.containerCmd }}" ]
          env:
            - name: DJANGO_CSRF_TRUSTED_ORIGINS
              value: {{ include "csrf.trusted.origins" . }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.debug }}"
            - name: ENTITY_PROCESSING_ENABLED
              value: "{{ .Values.entityProcessingEnabled }}"
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.djangoSettingsModule }}"
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_HOST
              value: {{ .Values.db.host }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.db.passwordSecretKeyRef | nindent 18 }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.db.usernameSecretKeyRef | nindent 18 }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.celery.brokerUrl }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.celery.resultBackend }}
            - name: REPLICA1_POSTGRES_HOST
              value: "{{ .Values.db.replica1Host }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.ingestKafka.bootstrapServers }}"
            {{- if .Values.ingestKafka.rawMonitorTransactions.enabled }}
            - name: KAFKA_PRODUCER_RAW_MONITOR_TRANSACTION_ENABLED
              value: "{{ .Values.ingestKafka.rawMonitorTransactions.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.processedEvents.enabled }}
            - name: KAFKA_PRODUCER_PROCESSED_EVENT_ENABLED
              value: "{{ .Values.ingestKafka.processedEvents.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.processedMonitorTransactions.enabled }}
            - name: KAFKA_PRODUCER_PROCESSED_MONITOR_TRANSACTION_ENABLED
              value: "{{ .Values.ingestKafka.processedMonitorTransactions.enabled }}"
            {{- end }}
            {{- if .Values.eventStreamProcessing.enabled }}
            - name: EVENT_STREAM_PROCESSING_ENABLED
              value: "{{ .Values.eventStreamProcessing.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.rawEventStream.enabled }}
            - name: KAFKA_PRODUCE_RAW_EVENT_STREAM_ENABLED
              value: "{{ .Values.ingestKafka.rawEventStream.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.accountRawEventStream.enabled }}
            - name: KAFKA_PRODUCE_ACCOUNT_RAW_EVENT_STREAM_ENABLED
              value: "{{ .Values.ingestKafka.accountRawEventStream.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.filteredEventStream.enabled }}
            - name: KAFKA_PRODUCE_FILTERED_EVENT_STREAM_ENABLED
              value: "{{ .Values.ingestKafka.filteredEventStream.enabled }}"
            {{- end }}
            {{- if .Values.ingestKafka.parsedEventStream.enabled }}
            - name: KAFKA_PRODUCE_PARSED_EVENT_STREAM_ENABLED
              value: "{{ .Values.ingestKafka.parsedEventStream.enabled }}"
            {{- end }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.aws.accessKeyIdSecretKeyRef | nindent 18 }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.aws.secretAccessKeySecretKeyRef | nindent 18 }}
            {{ if .Values.serverSecretKeyRef.name }}
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.serverSecretKeyRef | nindent 20 }}
            {{end}}
            {{- if .Values.ingestKafka.rawEvents.enabled }}
            - name: KAFKA_PRODUCER_RAW_EVENT_ENABLED
              value: "{{ .Values.ingestKafka.rawEvents.enabled }}"
            {{- end }}
            {{- if .Values.kafkaConsumer.enabled }}
            - name: KAFKA_CONSUMER
              value: {{ .Values.kafkaConsumer.consumer }}
            - name: KAFKA_CONSUMER_GROUP
              value: {{ .Values.kafkaConsumer.consumerGroup }}
            {{- end }}
            - name: CACHE_BACKEND
              value: {{ .Values.cache.backend }}
            - name: REDIS_URL
              value: {{ .Values.cache.redisUrl }}
            {{- if .Values.cache.eventTypeCache.enabled }}
            - name: EVENT_TYPE_CACHE_ENABLED
              value: "True"
            {{- end }}
            {{- if .Values.cache.eventTypeCache.enabled }}
            - name: EVENT_KEY_CACHE_ENABLED
              value: "True"
            {{- end }}
            {{- if .Values.clickhouse.enabled }}
            - name: CLICKHOUSE_HOST
              value: {{ .Values.clickhouse.host }}
            - name: CLICKHOUSE_PORT
              value: "{{ .Values.clickhouse.port }}"
            - name: CLICKHOUSE_SECURE
              value: "{{ .Values.clickhouse.secure }}"
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.clickhouse.passwordSecretKeyRef | nindent 18 }}
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- toYaml .Values.clickhouse.usernameSecretKeyRef | nindent 18 }}
            {{- end }}
          {{- if .Values.deployment.containerPort }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
