{{- if .Values.service.port -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingest.fullname" . }}
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ingest.selectorLabels" . | nindent 4 }}
{{- end}}