# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/kafka/event_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos.event import schema_pb2 as protos_dot_event_dot_schema__pb2
from protos.event import base_pb2 as protos_dot_event_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/kafka/event_stream.proto\x12\x0cprotos.kafka\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19protos/event/schema.proto\x1a\x17protos/event/base.proto\"\xa0\x02\n\x0bStreamEvent\x12.\n\x08uuid_str\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x0c\x65vent_source\x18\x03 \x01(\x0e\x32\x1f.protos.event.Event.EventSource\x12$\n\x1crecorded_ingestion_timestamp\x18\x04 \x01(\x10\x12,\n\x04type\x18\x05 \x01(\x0e\x32\x1e.protos.kafka.StreamEvent.Type\")\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06STRING\x10\x01\x12\x08\n\x04JSON\x10\x02\"\x1a\n\x18RawEventStreamPayloadKey\"x\n\x1aRawEventStreamPayloadValue\x12\x30\n\naccount_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12(\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x19.protos.kafka.StreamEvent\"\x1f\n\x1d\x46ilteredEventStreamPayloadKey\"\xae\x01\n\x1f\x46ilteredEventStreamPayloadValue\x12\x30\n\naccount_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12/\n\tfilter_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12(\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x19.protos.kafka.StreamEventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kafka.event_stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAMEVENT._serialized_start=134
  _STREAMEVENT._serialized_end=422
  _STREAMEVENT_TYPE._serialized_start=381
  _STREAMEVENT_TYPE._serialized_end=422
  _RAWEVENTSTREAMPAYLOADKEY._serialized_start=424
  _RAWEVENTSTREAMPAYLOADKEY._serialized_end=450
  _RAWEVENTSTREAMPAYLOADVALUE._serialized_start=452
  _RAWEVENTSTREAMPAYLOADVALUE._serialized_end=572
  _FILTEREDEVENTSTREAMPAYLOADKEY._serialized_start=574
  _FILTEREDEVENTSTREAMPAYLOADKEY._serialized_end=605
  _FILTEREDEVENTSTREAMPAYLOADVALUE._serialized_start=608
  _FILTEREDEVENTSTREAMPAYLOADVALUE._serialized_end=782
# @@protoc_insertion_point(module_scope)
