"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.kafka.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EventEntityPayloadKey(google.protobuf.message.Message):
    """Publish on `event_entity` topic"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___EventEntityPayloadKey = EventEntityPayloadKey

@typing_extensions.final
class EventEntityPayloadValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    DISCOVERED_ENTITY_INSTANCES_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def event(self) -> protos.kafka.base_pb2.ProcessedIngestionEvent: ...
    @property
    def discovered_entity_instances(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.kafka.base_pb2.DiscoveredEntityInstance]: ...
    def __init__(
        self,
        *,
        account_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        event: protos.kafka.base_pb2.ProcessedIngestionEvent | None = ...,
        discovered_entity_instances: collections.abc.Iterable[protos.kafka.base_pb2.DiscoveredEntityInstance] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "event", b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "discovered_entity_instances", b"discovered_entity_instances", "event", b"event"]) -> None: ...

global___EventEntityPayloadValue = EventEntityPayloadValue
