# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/kafka/processed_monitor_transactions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from protos.kafka import base_pb2 as protos_dot_kafka_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1protos/kafka/processed_monitor_transactions.proto\x12\x0cprotos.kafka\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17protos/kafka/base.proto\"\'\n%ProcessedMonitorTransactionPayloadKey\"\xad\x01\n\'ProcessedMonitorTransactionPayloadValue\x12\x30\n\naccount_id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12P\n\x1dprocessed_monitor_transaction\x18\x02 \x01(\x0b\x32).protos.kafka.ProcessedMonitorTransactionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kafka.processed_monitor_transactions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSEDMONITORTRANSACTIONPAYLOADKEY._serialized_start=124
  _PROCESSEDMONITORTRANSACTIONPAYLOADKEY._serialized_end=163
  _PROCESSEDMONITORTRANSACTIONPAYLOADVALUE._serialized_start=166
  _PROCESSEDMONITORTRANSACTIONPAYLOADVALUE._serialized_end=339
# @@protoc_insertion_point(module_scope)
