"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import protos.event.monitor_pb2
import protos.kafka.base_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class RawMonitorTransactionPayloadKey(google.protobuf.message.Message):
    """Publish on `raw_monitor_transactions` topic"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    MONITOR_ID_FIELD_NUMBER: builtins.int
    TRANSACTION_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def monitor_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def transaction(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        account_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        monitor_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        transaction: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "monitor_id", b"monitor_id", "transaction", b"transaction"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "monitor_id", b"monitor_id", "transaction", b"transaction"]) -> None: ...

global___RawMonitorTransactionPayloadKey = RawMonitorTransactionPayloadKey

@typing_extensions.final
class RawMonitorTransactionPayloadValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNT_ID_FIELD_NUMBER: builtins.int
    MONITOR_ID_FIELD_NUMBER: builtins.int
    TRANSACTION_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    TRANSACTION_EVENT_TYPE_FIELD_NUMBER: builtins.int
    DISCOVERED_ENTITY_INSTANCES_FIELD_NUMBER: builtins.int
    @property
    def account_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def monitor_id(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
    @property
    def transaction(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def event(self) -> protos.kafka.base_pb2.ProcessedIngestionEvent: ...
    transaction_event_type: protos.event.monitor_pb2.MonitorTransaction.MonitorTransactionEventType.ValueType
    @property
    def discovered_entity_instances(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[protos.kafka.base_pb2.DiscoveredEntityInstance]: ...
    def __init__(
        self,
        *,
        account_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        monitor_id: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        transaction: google.protobuf.wrappers_pb2.StringValue | None = ...,
        event: protos.kafka.base_pb2.ProcessedIngestionEvent | None = ...,
        transaction_event_type: protos.event.monitor_pb2.MonitorTransaction.MonitorTransactionEventType.ValueType = ...,
        discovered_entity_instances: collections.abc.Iterable[protos.kafka.base_pb2.DiscoveredEntityInstance] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "event", b"event", "monitor_id", b"monitor_id", "transaction", b"transaction"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_id", b"account_id", "discovered_entity_instances", b"discovered_entity_instances", "event", b"event", "monitor_id", b"monitor_id", "transaction", b"transaction", "transaction_event_type", b"transaction_event_type"]) -> None: ...

global___RawMonitorTransactionPayloadValue = RawMonitorTransactionPayloadValue
