version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  clickhouse:
    image: clickhouse/clickhouse-server:22.6-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    expose:
      - '8123'
    environment:
      - "CLICKHOUSE_DB=default"
      - "CLICKHOUSE_USER=default"
      - "CLICKHOUSE_PASSWORD=password"
      - "CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse:cached

  clickhouse-init:
    image: clickhouse/clickhouse-server:22.6-alpine
    volumes:
      - clickhouse_data:/var/lib/clickhouse:cached
    depends_on:
      - clickhouse
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      while ! clickhouse-client --host clickhouse --user default --password password -q \"SHOW databases;\"; do
          echo waiting for clickhouse up
          sleep 1
      done
      
      echo create DB
      clickhouse-client --host clickhouse --user default --password password -q \"CREATE DATABASE IF NOT EXISTS default;\";
      
      echo Using DB
      clickhouse-client --host clickhouse --user default --password password -q \"USE default;\";
                              
      echo Create Table
      clickhouse-client --host clickhouse --user default --password password --multiquery --query=\"
        SET allow_experimental_object_type=1;
        CREATE TABLE IF NOT EXISTS events (
              id UInt64,
              account_id UInt64,
              created_at DateTime64(3, 'UTC') default now(),
              timestamp DateTime64(3, 'UTC') default now(),
              event_type_id UInt64,
              event_type_name VARCHAR(256),
              event_source UInt16,
              processed_kvs JSON,
              ingested_event  String
          )
          ENGINE = MergeTree()
          PARTITION BY toDate(timestamp)
          ORDER BY (account_id, event_type_id, timestamp)
          PRIMARY KEY (account_id, event_type_id, timestamp)
          TTL toDateTime(created_at) + INTERVAL 10 DAY DELETE;\";
      
      echo Done Table
      exit 0
      "
      
  db:
    image: postgres:11
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=pass"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  clickhouse_data: