export const EVENT_TYPES = {
  DELAYED_EVENT: 'DELAYED_EVENT',
  MISSING_EVENT: 'MISSING_EVENT',
  PER_EVENT: 'PER_EVENT'
};

export const EVENT_TYPE_DISPLAY = {
  [EVENT_TYPES.DELAYED_EVENT]: 'Aggregated Events',
  [EVENT_TYPES.MISSING_EVENT]: 'Per Event',
  [EVENT_TYPES.PER_EVENT]: 'Per Event'
};

export const TRANSACTIONS_TYPE = {
  DELAYED_TRANSACTION: 'DELAYED_TRANSACTION',
  MISSING_TRANSACTION: 'MISSING_TRANSACTION'
};
