"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SqsConsumer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    QUEUE_URL_FIELD_NUMBER: builtins.int
    MAX_NUMBER_OF_MESSAGES_FIELD_NUMBER: builtins.int
    WAIT_TIME_SECONDS_FIELD_NUMBER: builtins.int
    @property
    def enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def queue_url(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def max_number_of_messages(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def wait_time_seconds(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    def __init__(
        self,
        *,
        enabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        queue_url: google.protobuf.wrappers_pb2.StringValue | None = ...,
        max_number_of_messages: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        wait_time_seconds: google.protobuf.wrappers_pb2.Int64Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["enabled", b"enabled", "max_number_of_messages", b"max_number_of_messages", "queue_url", b"queue_url", "wait_time_seconds", b"wait_time_seconds"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled", "max_number_of_messages", b"max_number_of_messages", "queue_url", b"queue_url", "wait_time_seconds", b"wait_time_seconds"]) -> None: ...

global___SqsConsumer = SqsConsumer

@typing_extensions.final
class PipelineConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HTTP_SERVER_FIELD_NUMBER: builtins.int
    BATCHER_FIELD_NUMBER: builtins.int
    EXPORTER_FIELD_NUMBER: builtins.int
    SQS_CONSUMER_FIELD_NUMBER: builtins.int
    @property
    def http_server(self) -> global___HttpServer: ...
    @property
    def batcher(self) -> global___Batcher: ...
    @property
    def exporter(self) -> global___WrappedExporter: ...
    @property
    def sqs_consumer(self) -> global___SqsConsumer: ...
    def __init__(
        self,
        *,
        http_server: global___HttpServer | None = ...,
        batcher: global___Batcher | None = ...,
        exporter: global___WrappedExporter | None = ...,
        sqs_consumer: global___SqsConsumer | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["batcher", b"batcher", "exporter", b"exporter", "http_server", b"http_server", "sqs_consumer", b"sqs_consumer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["batcher", b"batcher", "exporter", b"exporter", "http_server", b"http_server", "sqs_consumer", b"sqs_consumer"]) -> None: ...

global___PipelineConfig = PipelineConfig

@typing_extensions.final
class NetAddr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENDPOINT_FIELD_NUMBER: builtins.int
    TRANSPORT_FIELD_NUMBER: builtins.int
    @property
    def endpoint(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def transport(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        endpoint: google.protobuf.wrappers_pb2.StringValue | None = ...,
        transport: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["endpoint", b"endpoint", "transport", b"transport"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["endpoint", b"endpoint", "transport", b"transport"]) -> None: ...

global___NetAddr = NetAddr

@typing_extensions.final
class HttpServer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NET_ADDR_FIELD_NUMBER: builtins.int
    @property
    def net_addr(self) -> global___NetAddr: ...
    def __init__(
        self,
        *,
        net_addr: global___NetAddr | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["net_addr", b"net_addr"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["net_addr", b"net_addr"]) -> None: ...

global___HttpServer = HttpServer

@typing_extensions.final
class Batcher(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHAN_SIZE_FIELD_NUMBER: builtins.int
    BATCH_SIZE_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    @property
    def chan_size(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    @property
    def batch_size(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    @property
    def timeout(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        chan_size: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
        batch_size: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
        timeout: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["batch_size", b"batch_size", "chan_size", b"chan_size", "timeout", b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["batch_size", b"batch_size", "chan_size", b"chan_size", "timeout", b"timeout"]) -> None: ...

global___Batcher = Batcher

@typing_extensions.final
class WrappedExporter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Wrapper(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONSOLE_EXPORTER_FIELD_NUMBER: builtins.int
        HTTP_EXPORTER_FIELD_NUMBER: builtins.int
        @property
        def console_exporter(self) -> global___ConsoleExporter: ...
        @property
        def http_exporter(self) -> global___HttpExporter: ...
        def __init__(
            self,
            *,
            console_exporter: global___ConsoleExporter | None = ...,
            http_exporter: global___HttpExporter | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["console_exporter", b"console_exporter", "http_exporter", b"http_exporter", "wrapper", b"wrapper"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["console_exporter", b"console_exporter", "http_exporter", b"http_exporter", "wrapper", b"wrapper"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["wrapper", b"wrapper"]) -> typing_extensions.Literal["console_exporter", "http_exporter"] | None: ...

    @typing_extensions.final
    class WrappersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___WrappedExporter.Wrapper: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___WrappedExporter.Wrapper | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    WRAPPERS_FIELD_NUMBER: builtins.int
    @property
    def wrappers(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___WrappedExporter.Wrapper]: ...
    def __init__(
        self,
        *,
        wrappers: collections.abc.Mapping[builtins.str, global___WrappedExporter.Wrapper] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["wrappers", b"wrappers"]) -> None: ...

global___WrappedExporter = WrappedExporter

@typing_extensions.final
class ConsoleExporter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    @property
    def enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        enabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["enabled", b"enabled"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled"]) -> None: ...

global___ConsoleExporter = ConsoleExporter

@typing_extensions.final
class BearerAuth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    SCHEME_FIELD_NUMBER: builtins.int
    @property
    def token(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def scheme(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        token: google.protobuf.wrappers_pb2.StringValue | None = ...,
        scheme: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["scheme", b"scheme", "token", b"token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["scheme", b"scheme", "token", b"token"]) -> None: ...

global___BearerAuth = BearerAuth

@typing_extensions.final
class Authentication(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BEARER_AUTH_FIELD_NUMBER: builtins.int
    @property
    def bearer_auth(self) -> global___BearerAuth: ...
    def __init__(
        self,
        *,
        bearer_auth: global___BearerAuth | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["auth", b"auth", "bearer_auth", b"bearer_auth"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["auth", b"auth", "bearer_auth", b"bearer_auth"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["auth", b"auth"]) -> typing_extensions.Literal["bearer_auth"] | None: ...

global___Authentication = Authentication

@typing_extensions.final
class HttpExporter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    HOST_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    CHAN_SIZE_FIELD_NUMBER: builtins.int
    AUTHENTICATION_FIELD_NUMBER: builtins.int
    HEADERS_FIELD_NUMBER: builtins.int
    @property
    def host(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def endpoint(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def chan_size(self) -> google.protobuf.wrappers_pb2.UInt32Value: ...
    @property
    def authentication(self) -> global___Authentication: ...
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        host: google.protobuf.wrappers_pb2.StringValue | None = ...,
        endpoint: google.protobuf.wrappers_pb2.StringValue | None = ...,
        chan_size: google.protobuf.wrappers_pb2.UInt32Value | None = ...,
        authentication: global___Authentication | None = ...,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["authentication", b"authentication", "chan_size", b"chan_size", "endpoint", b"endpoint", "host", b"host"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["authentication", b"authentication", "chan_size", b"chan_size", "endpoint", b"endpoint", "headers", b"headers", "host", b"host"]) -> None: ...

global___HttpExporter = HttpExporter
